### PR TITLE
Clean the task text of context and tags

### PR DESCRIPTION
**Pull request by MarkRobbins**
Do not know if this was left in for development purposes or if it is a performance issue

### CODE REVIEW

**Comment by piascikj** [comment]
It used to work this way, but some people use their tags and contexts in sentences.

**Comment by piascikj** [comment]
I can see someone wanting this, but it would have to be configurable.

**Comment by jronallo** [comment]
I'm one who often writes a sentence of notes in a meeting, goes back to my notes afterwards and makes it a task, and then adds context and tags to words that are already in the sentence. When I'm working on code my mode changes and it would be nice to not have the duplication sometimes.

**Comment by piascikj** [comment]
The alternative to this is #67 . It would keep them in one place.

**Pull request closed without merging**
